import qrcode from "qrcode-generator";

/**
 * A QR code for `text` as an SVG element. Error correction L keeps a long
 * share link at the lowest module count, which scans best off a screen.
 */
export function qrSvg(text: string): SVGSVGElement {
  const qr = qrcode(0, "L");
  qr.addData(text, "Byte");
  qr.make();
  const template = document.createElement("template");
  // The markup is generated by the library from module data only: no user text is interpolated.
  template.innerHTML = qr.createSvgTag({ cellSize: 4, margin: 4, scalable: true });
  const svg = template.content.firstElementChild as SVGSVGElement;
  svg.setAttribute("role", "img");
  svg.setAttribute("aria-label", "分享連結的 QR code");
  svg.classList.add("block", "h-auto", "w-full", "bg-white");
  return svg;
}
