import type { Scene } from "../types";

const SEE_CARD = { jp: "この カード を {見|み}て ください。", zh: "請看這張卡（醫療卡）" };

/** 緊急・醫療. The medical and allergy cards themselves live on #/medical. */
export default {
  id: "emergency",
  title: "緊急・醫療",
  icon: "firstaid",
  groups: [
    { id: "body", title: "身體不舒服・看醫生" },
    { id: "lost", title: "東西掉了・被偷・找警察" },
    { id: "separated", title: "跟同伴走散了" },
    { id: "disaster", title: "地震・颱風・停電" },
  ],
  phrases: [
    { id: "emergency-help", group: "body", zh: "救命！請幫幫我！", jp: "{助|たす}けて ください！" },
    { id: "emergency-ambulance", group: "body", zh: "請幫我叫救護車。", jp: "{救急車|きゅうきゅうしゃ} を {呼|よ}んで ください。" },
    { id: "emergency-police", group: "lost", zh: "請幫我叫警察。", jp: "{警察|けいさつ} を {呼|よ}んで ください。" },
    { id: "emergency-unwell", group: "body", zh: "我身體不舒服。", jp: "{気分|きぶん} が {悪|わる}い です。" },
    {
      id: "emergency-medical-card",
      group: "body",
      zh: "這是我的醫療資料，請看這張卡。",
      jp: "{私|わたし} の {医療|いりょう} {情報|じょうほう} です。この カード を {見|み}て ください。",
      link: { href: "#/medical", label: "打開醫療卡" },
    },
    { id: "emergency-to-hospital", group: "body", zh: "請帶我去醫院。", jp: "{病院|びょういん} に {連|つ}れて {行|い}って ください。" },
    {
      id: "emergency-hospital-near",
      group: "body",
      zh: "附近的醫院在哪裡？",
      jp: "{近|ちか}く の {病院|びょういん} は どこ です か。",
      answers: "direction",
    },
    {
      id: "emergency-pharmacy-near",
      group: "body",
      zh: "附近有藥局嗎？",
      jp: "{近|ちか}く に {薬局|やっきょく} は あります か。",
      answers: "place",
    },
    {
      id: "emergency-insurance",
      group: "body",
      zh: "我有保旅遊保險。",
      jp: "{海外旅行|かいがいりょこう} {保険|ほけん} に {入|はい}って います。",
    },
    {
      id: "emergency-chinese-doctor",
      group: "body",
      zh: "有會說中文的醫生嗎？",
      jp: "{中国語|ちゅうごくご} が {話|はな}せる {医師|いし} は います か。",
      answers: "yesNo",
    },
    { id: "emergency-cost", group: "body", zh: "費用大約多少？", jp: "{費用|ひよう} は いくら ぐらい です か。" },
    {
      id: "emergency-documents",
      group: "body",
      zh: "請給我診斷書和收據（保險理賠要用）。",
      jp: "{保険|ほけん} の ため に {診断書|しんだんしょ} と {領収書|りょうしゅうしょ} を ください。",
      link: { href: "#/guide/medical-claim", label: "看理賠要準備的文件" },
    },
    {
      id: "emergency-english-certificate",
      group: "body",
      zh: "可以開英文的診斷書嗎？",
      jp: "{英語|えいご} の {診断書|しんだんしょ} を {書|か}いて いただけます か。",
      tip: "診斷書可能要另外付費，或要等幾天才拿得到。",
      answers: "yesNo",
    },
    {
      id: "emergency-itemized-bill",
      group: "body",
      zh: "請也給我費用明細。",
      jp: "{診療|しんりょう} {明細書|めいさいしょ} も ください。",
    },
    {
      id: "emergency-card-pay",
      group: "body",
      zh: "可以刷信用卡付嗎？",
      jp: "クレジットカード で {払|はら}えます か。",
      answers: "yesNo",
    },
    { id: "emergency-stolen", group: "lost", zh: "我的東西被偷了。", jp: "{物|もの} を {盗|ぬす}まれました。" },
    { id: "emergency-lost-wallet", group: "lost", zh: "我的錢包掉了。", jp: "{財布|さいふ} を なくしました。" },
    { id: "emergency-lost-passport", group: "lost", zh: "我的護照掉了。", jp: "パスポート を なくしました。" },
    {
      id: "emergency-evacuate",
      group: "disaster",
      zh: "（地震、颱風時）要去哪裡避難？",
      jp: "どこ に {避難|ひなん} すれば いい です か。",
      // Safety tips, the disaster-alert app supervised by the Japan Tourism Agency, in 15 languages
      // including Traditional Chinese. Source: Nagoya City, updated 2025-10,
      // https://www.city.nagoya.jp/bousaiportal/international/1037420.html (checked 2026-10-11).
      tip: "出發前可以下載觀光廳監修的「Safety tips」App（有繁體中文），地震、海嘯、颱風警報會推播通知。",
      answers: "direction",
    },
    {
      id: "emergency-safe-place",
      group: "disaster",
      zh: "哪裡比較安全？",
      jp: "{安全|あんぜん} な {場所|ばしょ} は どこ です か。",
      answers: "direction",
    },
    {
      id: "emergency-trains-running",
      group: "disaster",
      zh: "電車還有在開嗎？",
      jp: "{電車|でんしゃ} は {動|うご}いて います か。",
      answers: [
        { jp: "{動|うご}いて います", zh: "有在開" },
        { jp: "{止|と}まって います", zh: "停駛了" },
        { jp: "わかりません", zh: "不知道" },
      ],
    },
    {
      id: "emergency-charge-phone",
      group: "disaster",
      zh: "哪裡可以幫手機充電？",
      jp: "スマホ を {充電|じゅうでん} できる {場所|ばしょ} は あります か。",
      tip: "地震停電時，手機沒電是外國旅客最大的困擾之一。",
      answers: "place",
    },
    {
      id: "emergency-pay-card",
      group: "body",
      zh: "可以刷信用卡嗎？",
      jp: "クレジットカード で {払|はら}えます か。",
      tip: "日本很多醫院和診所只收現金，看病前先問。",
      answers: "yesNo",
    },
    {
      id: "emergency-report-lost",
      group: "lost",
      zh: "我要登記遺失物。",
      jp: "{落|お}とし{物|もの} の {届|とど}け{出|で} を したい です。",
      tip: "到派出所（交番）或車站窗口。先想好：什麼時候、在哪裡、東西長什麼樣子。",
    },
    {
      id: "emergency-found-call-hotel",
      group: "lost",
      zh: "找到的話，請聯絡這間飯店。",
      jp: "{見|み}つかったら、この ホテル に {連絡|れんらく} して ください。",
      link: { href: "#/hotel", label: "打開飯店卡給對方看" },
    },
    {
      id: "emergency-separated",
      group: "separated",
      zh: "我跟同伴走散了。",
      jp: "{連|つ}れ と はぐれて しまいました。",
      tip: "先待在原地或約好的地方，不要一直走動。",
    },
    {
      id: "emergency-announce",
      group: "separated",
      zh: "可以幫我廣播找人嗎？",
      jp: "{館内|かんない} {放送|ほうそう} で {呼|よ}び{出|だ}して いただけます か。",
      tip: "在車站、百貨公司、機場可以請服務台廣播。",
      answers: "yesNo",
    },
    {
      id: "emergency-wait-here",
      group: "separated",
      zh: "我可以在這裡等嗎？",
      jp: "ここ で {待|ま}って いて も いい です か。",
      answers: "yesNo",
    },
  ],
  heard: [
    {
      id: "emergency-heard-where-hurts",
      jp: "どこ が {痛|いた}い です か。",
      zh: "哪裡痛？",
      replies: [
        { jp: "{頭|あたま} です。", zh: "頭" },
        { jp: "{胸|むね} です。", zh: "胸口" },
        { jp: "お{腹|なか} です。", zh: "肚子" },
        { jp: "{足|あし} です。", zh: "腳" },
        { jp: "{腰|こし} です。", zh: "腰" },
      ],
    },
    {
      id: "emergency-heard-since",
      jp: "いつ から です か。",
      zh: "從什麼時候開始的？",
      replies: [
        { jp: "さっき から です。", zh: "剛剛" },
        { jp: "{今朝|けさ} から です。", zh: "今天早上" },
        { jp: "{昨日|きのう} から です。", zh: "昨天" },
      ],
    },
    {
      id: "emergency-heard-insurance",
      jp: "{保険|ほけん} は あります か。",
      zh: "有保險嗎？",
      replies: [
        { jp: "{海外旅行|かいがいりょこう} {保険|ほけん} が あります。", zh: "有旅遊保險" },
        { jp: "ありません。", zh: "沒有" },
      ],
    },
    {
      id: "emergency-heard-allergy",
      jp: "アレルギー は あります か。",
      zh: "有過敏嗎？",
      replies: [{ jp: "ありません。", zh: "沒有" }, SEE_CARD],
    },
    {
      id: "emergency-heard-meds",
      jp: "{普段|ふだん} {飲|の}んで いる {薬|くすり} は あります か。",
      zh: "平常有在吃藥嗎？",
      replies: [{ jp: "ありません。", zh: "沒有" }, SEE_CARD],
    },
    {
      id: "emergency-heard-family",
      jp: "ご{家族|かぞく} の {連絡先|れんらくさき} を {教|おし}えて ください。",
      zh: "請告訴我家人的聯絡方式。",
      replies: [
        { jp: "この {画面|がめん} を {見|み}て ください。", zh: "請看這個畫面（打開求救卡）" },
        { jp: "{家族|かぞく} は {日本|にほん} に いません。", zh: "家人不在日本" },
      ],
    },
    {
      id: "emergency-heard-when-where",
      jp: "いつ、どこ で なくしました か。",
      zh: "什麼時候、在哪裡弄丟的？",
      replies: [
        { jp: "さっき です。", zh: "剛剛" },
        { jp: "{今日|きょう} です。", zh: "今天" },
        { jp: "{電車|でんしゃ} の {中|なか} です。", zh: "在電車上" },
        { jp: "わかりません。", zh: "不知道" },
      ],
    },
    {
      id: "emergency-heard-calm",
      jp: "{落|お}ち{着|つ}いて ください。",
      zh: "請冷靜。",
      replies: [
        { jp: "はい。", zh: "好" },
        { jp: "どこ に {行|い}けば いい です か。", zh: "我要去哪裡？" },
      ],
    },
    {
      id: "emergency-heard-higher-ground",
      jp: "{高|たか}い {所|ところ} に {逃|に}げて ください。",
      zh: "請往高的地方逃（海嘯警報）。",
      replies: [
        { jp: "わかりました。", zh: "知道了" },
        { jp: "どっち です か。", zh: "往哪邊？" },
      ],
    },
  ],
} satisfies Scene;
