import type { Scene } from "../types";

const OK = { jp: "わかりました。", zh: "知道了" };

/** 帶小孩: babies and young children, from strollers on trains to a child who has gone missing. */
export default {
  id: "family",
  title: "帶小孩",
  icon: "stroller",
  groups: [
    { id: "lost", title: "走失・生病" },
    { id: "out", title: "外出・電車" },
    { id: "eat", title: "吃飯" },
    { id: "care", title: "尿布・哺乳・廁所" },
  ],
  phrases: [
    {
      id: "family-lost-child",
      group: "lost",
      zh: "我的小孩走失了，請幫我一起找。",
      jp: "{子|こ}ども が {迷子|まいご} に なりました。{一緒|いっしょ} に {探|さが}して ください。",
      tip: "馬上告訴最近的店員或站務員，請他們廣播。找不到時打 110 或到派出所（交番）。",
      link: { href: "#/help", label: "打開求救卡（110・家人電話）" },
    },
    {
      id: "family-announce",
      group: "lost",
      zh: "可以幫我廣播找小孩嗎？",
      jp: "{子|こ}ども を {放送|ほうそう} で {呼|よ}び{出|だ}して いただけます か。",
      answers: "yesNo",
    },
    {
      id: "family-fever",
      group: "lost",
      zh: "小孩發燒了。",
      jp: "{子|こ}ども が {熱|ねつ} を {出|だ}しました。",
    },
    {
      id: "family-pediatrics",
      group: "lost",
      zh: "附近有小兒科嗎？",
      jp: "{近|ちか}く に {小児科|しょうにか} は あります か。",
      answers: "place",
    },
    {
      id: "family-kids-medicine",
      group: "lost",
      zh: "有小孩可以吃的藥嗎？",
      jp: "{子|こ}ども {用|よう} の {薬|くすり} は あります か。",
      tip: "同時告訴藥師小孩的年齡和體重。",
      answers: "yesNo",
    },
    {
      id: "family-stroller-elevator",
      group: "out",
      zh: "推嬰兒車可以搭的電梯在哪裡？",
      jp: "ベビーカー で {乗|の}れる エレベーター は どこ です か。",
      answers: "direction",
    },
    {
      id: "family-stroller-fold",
      group: "out",
      zh: "嬰兒車需要收起來嗎？",
      jp: "ベビーカー は たたんだ ほう が いい です か。",
      answers: "yesNo",
    },
    {
      id: "family-stroller-rent",
      group: "out",
      zh: "可以借嬰兒車嗎？",
      jp: "ベビーカー を {借|か}りられます か。",
      tip: "機場、百貨公司、大型商場和部分景點有嬰兒車可以借，問服務台。",
      answers: "yesNo",
    },
    {
      id: "family-child-fare",
      group: "out",
      zh: "小孩要買票嗎？",
      jp: "{子|こ}ども の {切符|きっぷ} は {必要|ひつよう} です か。",
      tip: "日本的鐵路大多是學齡前小孩由大人陪同時免費、小學生半價，但各家規定不同，問站務員最準。",
      answers: "yesNo",
    },
    {
      id: "family-preschooler",
      group: "out",
      zh: "小孩還沒上小學。",
      jp: "この {子|こ} は まだ {小学生|しょうがくせい} では ありません。",
    },
    {
      id: "family-kids-chair",
      group: "eat",
      zh: "有兒童椅嗎？",
      jp: "{子|こ}ども {用|よう} の {椅子|いす} は あります か。",
      answers: "yesNo",
    },
    {
      id: "family-kids-tableware",
      group: "eat",
      zh: "請給我兒童用的盤子和湯匙。",
      jp: "{子|こ}ども {用|よう} の お{皿|さら} と スプーン を ください。",
    },
    {
      id: "family-kids-menu",
      group: "eat",
      zh: "有兒童餐嗎？",
      jp: "お{子|こ}さま メニュー は あります か。",
      answers: "yesNo",
    },
    {
      id: "family-stroller-inside",
      group: "eat",
      zh: "可以推嬰兒車進去嗎？",
      jp: "ベビーカー の まま {入|はい}れます か。",
      answers: "yesNo",
    },
    {
      id: "family-baby-food",
      group: "eat",
      zh: "可以帶寶寶的副食品進來吃嗎？",
      jp: "{離乳食|りにゅうしょく} を {持|も}ち{込|こ}んで も いい です か。",
      answers: "yesNo",
    },
    {
      id: "family-hot-water",
      group: "eat",
      zh: "可以給我泡奶用的熱水嗎？",
      jp: "ミルク {用|よう} の お{湯|ゆ} を いただけます か。",
      answers: "yesNo",
    },
    {
      id: "family-cut-small",
      group: "eat",
      zh: "可以幫我切成小塊嗎？",
      jp: "{小|ちい}さく {切|き}って いただけます か。",
      answers: "yesNo",
    },
    {
      id: "family-diaper-change",
      group: "care",
      zh: "哪裡可以換尿布？",
      jp: "おむつ を {替|か}えられる {場所|ばしょ} は あります か。",
      answers: "place",
    },
    {
      id: "family-nursing-room",
      group: "care",
      zh: "哺乳室在哪裡？",
      jp: "{授乳室|じゅにゅうしつ} は どこ です か。",
      tip: "車站、百貨公司和大型商場的「ベビー休憩室」通常有哺乳室、尿布台和熱水。",
      answers: "direction",
    },
    {
      id: "family-buy-diapers",
      group: "care",
      zh: "哪裡買得到尿布？",
      jp: "おむつ は どこ で {買|か}えます か。",
      answers: [
        { jp: "ドラッグストア", zh: "藥妝店" },
        { jp: "コンビニ", zh: "便利商店" },
        { jp: "この {近|ちか}く", zh: "就在附近" },
        { jp: "ありません", zh: "這附近沒有" },
        { jp: "わかりません", zh: "不知道" },
      ],
    },
    {
      id: "family-toilet-urgent",
      group: "care",
      zh: "小孩急著上廁所，附近有廁所嗎？",
      jp: "{子|こ}ども が トイレ に {行|い}きたい です。{近|ちか}く に あります か。",
      answers: "place",
    },
  ],
  heard: [
    {
      id: "family-heard-describe",
      jp: "お{子|こ}さん の {年|とし} と {服|ふく} の {色|いろ} を {教|おし}えて ください。",
      zh: "請告訴我小孩的年齡和衣服的顏色。",
      replies: [
        { jp: "{写真|しゃしん} が あります。", zh: "我有照片（給對方看手機）" },
        { jp: "{紙|かみ} に {書|か}きます。", zh: "我寫在紙上" },
      ],
    },
    {
      id: "family-heard-how-old",
      jp: "お{子|こ}さん は {何歳|なんさい} です か。",
      zh: "小孩幾歲？",
      replies: [
        { jp: "{1歳|いっさい} {未満|みまん} です。", zh: "不到 1 歲" },
        { jp: "まだ {小学生|しょうがくせい} では ありません。", zh: "還沒上小學" },
        { jp: "{小学生|しょうがくせい} です。", zh: "小學生" },
        { jp: "{中学生|ちゅうがくせい} {以上|いじょう} です。", zh: "國中以上" },
        { jp: "{紙|かみ} に {書|か}きます。", zh: "我寫在紙上" },
      ],
    },
    {
      id: "family-heard-fold",
      jp: "ベビーカー は たたんで ください。",
      zh: "請把嬰兒車收起來。",
      replies: [OK, { jp: "{手伝|てつだ}って いただけます か。", zh: "可以幫我一下嗎？" }],
    },
    {
      id: "family-heard-free",
      jp: "{未就学|みしゅうがく} の お{子|こ}さん は {無料|むりょう} です。",
      zh: "還沒上小學的小孩免費。",
      replies: [OK, { jp: "ありがとう ございます。", zh: "謝謝" }],
    },
    {
      id: "family-heard-no-stroller",
      jp: "{店内|てんない} に ベビーカー は {入|はい}れません。",
      zh: "嬰兒車不能推進店裡。",
      replies: [
        { jp: "どこ に {置|お}けば いい です か。", zh: "要放在哪裡？" },
        OK,
      ],
    },
  ],
} satisfies Scene;
