import type { Scene } from "../types";

/** 交通: the scene that matters most, so it goes deepest. */
export default {
  id: "transport",
  title: "交通",
  icon: "train",
  groups: [
    { id: "where", title: "問路・去哪裡" },
    { id: "elevator", title: "電梯・不走樓梯" },
    { id: "train", title: "月台・搭車" },
    { id: "ticket", title: "車票・閘門・坐過站" },
    { id: "bus-taxi", title: "公車・計程車" },
    { id: "lost", title: "東西掉了" },
  ],
  phrases: [
    {
      id: "transport-want-to-go",
      group: "where",
      zh: "我想去〇〇。",
      jp: "$dest に {行|い}きたい です。",
      fallback: "ここ に {行|い}きたい です。",
      fallbackZh: "我想去這裡。（同時給對方看地址或地圖）",
      answers: "direction",
    },
    {
      id: "transport-how-to-go",
      group: "where",
      zh: "去〇〇要怎麼走？",
      jp: "$dest へ は どう {行|い}けば いい です か。",
      fallback: "ここ へ は どう {行|い}けば いい です か。",
      fallbackZh: "去這裡要怎麼走？（同時給對方看地址或地圖）",
      answers: "direction",
    },
    {
      id: "transport-stops-at",
      group: "train",
      zh: "這班車有停〇〇嗎？",
      jp: "この {電車|でんしゃ} は $stop に {止|と}まります か。",
      fallback: "この {電車|でんしゃ} は ここ に {止|と}まります か。",
      fallbackZh: "這班車有停這裡嗎？（同時給對方看站名）",
      tip: "上車前問月台上的站務員或旁邊的人。",
      answers: "yesNo",
    },
    {
      id: "transport-every-stop",
      group: "train",
      zh: "這班車每一站都停嗎？",
      jp: "この {電車|でんしゃ} は {各駅|かくえき} に {止|と}まります か。",
      tip: "快速、急行、特急不是每站都停，這是最常搭錯車的原因。",
      answers: "yesNo",
    },
    {
      id: "transport-which-platform",
      group: "train",
      zh: "去〇〇的車在幾號月台？",
      jp: "$stop へ {行|い}く {電車|でんしゃ} は {何番線|なんばんせん} です か。",
      fallback: "ここ へ {行|い}く {電車|でんしゃ} は {何番線|なんばんせん} です か。",
      fallbackZh: "去這裡的車在幾號月台？（同時給對方看站名）",
      answers: "platform",
    },
    {
      id: "transport-which-line",
      group: "train",
      zh: "去〇〇要搭哪一條線？",
      jp: "$stop へ は {何線|なにせん} に {乗|の}れば いい です か。",
      fallback: "ここ へ は {何線|なにせん} に {乗|の}れば いい です か。",
      fallbackZh: "去這裡要搭哪一條線？",
    },
    {
      id: "transport-transfer",
      group: "train",
      zh: "去〇〇要在哪裡換車？",
      jp: "$stop へ は どこ で {乗|の}り{換|か}えます か。",
      fallback: "ここ へ は どこ で {乗|の}り{換|か}えます か。",
      fallbackZh: "去這裡要在哪裡換車？",
    },
    {
      id: "transport-transfer-gate",
      group: "train",
      zh: "轉車要先出剪票口嗎？",
      jp: "{乗|の}り{換|か}え は {改札|かいさつ} を {出|で}ます か。",
      answers: "yesNo",
    },
    {
      id: "transport-transfer-where",
      group: "train",
      zh: "轉乘口在哪裡？",
      jp: "{乗|の}り{換|か}え{口|ぐち} は どこ です か。",
      tip: "轉乘口是不用出站就能換車的閘門，通常有轉乘路線的顏色標示。",
      answers: "direction",
    },
    {
      id: "transport-how-long",
      group: "train",
      zh: "到〇〇要多久？",
      jp: "$stop まで どのくらい かかります か。",
      fallback: "ここ まで どのくらい かかります か。",
      fallbackZh: "到這裡要多久？",
      answers: "time",
    },
    {
      id: "transport-fare",
      group: "ticket",
      zh: "到〇〇要多少錢？",
      jp: "$stop まで いくら です か。",
      fallback: "ここ まで いくら です か。",
      fallbackZh: "到這裡要多少錢？",
    },
    {
      id: "transport-tell-me-when",
      group: "train",
      zh: "到〇〇的時候請告訴我。",
      jp: "$stop に {着|つ}いたら {教|おし}えて ください。",
      fallback: "ここ に {着|つ}いたら {教|おし}えて ください。",
      fallbackZh: "到這裡的時候請告訴我。",
      tip: "搭公車或計程車時很好用。",
    },
    {
      id: "transport-rode-past",
      group: "ticket",
      zh: "我坐過站了，該怎麼辦？",
      jp: "{乗|の}り{過|す}ごして しまいました。どう すれば いい です か。",
      tip: "在月台或出站閘門旁的站務員窗口問。",
    },
    {
      id: "transport-wrong-ticket",
      group: "ticket",
      zh: "我買錯票了。",
      jp: "{切符|きっぷ} を {間違|まちが}えて {買|か}って しまいました。",
      tip: "拿著車票到閘門旁的站務員窗口。",
    },
    {
      id: "transport-ic-short",
      group: "ticket",
      zh: "交通卡餘額不夠，補票機在哪裡？",
      jp: "{IC|アイシー}カード の {残高|ざんだか} が {足|た}りません。{精算機|せいさんき} は どこ です か。",
      tip: "出站閘門擋住、發出聲音時用。補票機（精算機）通常在閘門旁邊。",
      answers: "direction",
    },
    {
      id: "transport-gate-stuck",
      group: "ticket",
      zh: "我過不了閘門。",
      jp: "{改札|かいさつ} を {通|とお}れません。",
    },
    {
      id: "transport-where-charge",
      group: "ticket",
      zh: "交通卡在哪裡加值？",
      jp: "チャージ は どこ で できます か。",
      answers: "direction",
    },
    {
      id: "transport-how-to-buy",
      group: "ticket",
      zh: "請教我怎麼買票。",
      jp: "{切符|きっぷ} の {買|か}い{方|かた} を {教|おし}えて ください。",
    },
    {
      id: "transport-exit-for",
      group: "where",
      zh: "去〇〇要從哪個出口出去？",
      jp: "$dest に {行|い}く には どの {出口|でぐち} が {近|ちか}い です か。",
      fallback: "ここ に {行|い}く には どの {出口|でぐち} が {近|ちか}い です か。",
      fallbackZh: "去這裡要從哪個出口出去？（同時給對方看地址或地圖）",
      tip: "大車站的出口很多，先問好出口再走，比較不會繞路。",
      answers: "exit",
    },
    {
      id: "transport-nearest-exit",
      group: "where",
      zh: "離這個地址最近的出口是哪一個？",
      jp: "この {住所|じゅうしょ} に {一番|いちばん} {近|ちか}い {出口|でぐち} は どこ です か。",
      tip: "同時給對方看地址。",
      answers: "direction",
    },
    {
      id: "transport-elevator",
      group: "elevator",
      zh: "電梯在哪裡？",
      jp: "エレベーター は どこ です か。",
      answers: "direction",
    },
    {
      id: "transport-elevator-exit",
      group: "elevator",
      zh: "哪個出口有電梯？",
      jp: "エレベーター が ある {出口|でぐち} は どこ です か。",
      answers: "exit",
    },
    {
      id: "transport-elevator-platform",
      group: "elevator",
      zh: "到月台的電梯在哪裡？",
      jp: "ホーム へ の エレベーター は どこ です か。",
      answers: "direction",
    },
    {
      id: "transport-elevator-gate",
      group: "elevator",
      zh: "電梯在剪票口裡面還是外面？",
      jp: "エレベーター は {改札|かいさつ} の {中|なか} です か、{外|そと} です か。",
      tip: "很多車站的電梯分成剪票口內、外兩段，出站前先問清楚。",
      answers: [
        { jp: "{改札|かいさつ} の {中|なか}", zh: "在剪票口裡面" },
        { jp: "{改札|かいさつ} の {外|そと}", zh: "在剪票口外面" },
        { jp: "わかりません", zh: "不知道" },
      ],
    },
    {
      id: "transport-elevator-escort",
      group: "elevator",
      zh: "可以請站務員帶我去搭電梯嗎？",
      jp: "{駅員|えきいん} さん に エレベーター まで {案内|あんない} して いただけます か。",
      answers: "yesNo",
    },
    {
      id: "transport-bus-stop",
      group: "bus-taxi",
      zh: "去〇〇的公車在哪裡搭？",
      jp: "$stop {行|ゆ}き の バス {乗|の}り{場|ば} は どこ です か。",
      fallback: "バス {乗|の}り{場|ば} は どこ です か。",
      fallbackZh: "公車站在哪裡？",
      answers: "direction",
    },
    {
      id: "transport-taxi-stand",
      group: "bus-taxi",
      zh: "計程車招呼站在哪裡？",
      jp: "タクシー {乗|の}り{場|ば} は どこ です か。",
      answers: "direction",
    },
    {
      id: "transport-taxi-to",
      group: "bus-taxi",
      zh: "（計程車）請載我到〇〇。",
      jp: "$dest まで お{願|ねが}い します。",
      fallback: "この {住所|じゅうしょ} まで お{願|ねが}い します。",
      fallbackZh: "（計程車）請載我到這個地址。（同時給司機看地址）",
    },
    {
      id: "transport-taxi-card",
      group: "bus-taxi",
      zh: "（計程車）可以刷卡嗎？",
      jp: "カード で {払|はら}えます か。",
      tip: "上車前先問。小型車行和鄉下的計程車常常只收現金。",
      answers: "yesNo",
    },
    {
      id: "transport-taxi-receipt",
      group: "bus-taxi",
      zh: "請給我收據。",
      jp: "{領収書|りょうしゅうしょ} を ください。",
      tip: "收據上有車行的電話和車號，東西忘在車上時找得回來。",
    },
    {
      id: "transport-lost-item",
      group: "lost",
      zh: "我把東西忘在電車上了。",
      jp: "{電車|でんしゃ} に {忘|わす}れ{物|もの} を しました。",
      tip: "到站務員窗口說，並告訴對方幾點、從哪一站上車。",
    },
    {
      id: "transport-lost-in-taxi",
      group: "lost",
      zh: "我把東西忘在計程車上了。",
      jp: "タクシー に {忘|わす}れ{物|もの} を しました。",
      tip: "給對方看計程車收據，上面有車行電話。",
    },
    {
      id: "transport-last-train",
      group: "train",
      zh: "末班車是幾點？",
      jp: "{終電|しゅうでん} は {何時|なんじ} です か。",
    },
    {
      id: "transport-my-seat",
      group: "train",
      zh: "不好意思，這好像是我的位子。",
      jp: "すみません、ここ は {私|わたし} の {席|せき} だ と {思|おも}います。",
      tip: "同時給對方看車票上的車廂和座位號碼。",
    },
  ],
  heard: [
    {
      id: "transport-heard-elevator-outside",
      jp: "エレベーター は {改札|かいさつ} の {外|そと} に あります。",
      zh: "電梯在剪票口外面。",
      replies: [
        { jp: "わかりました。", zh: "知道了" },
        { jp: "{一度|いちど} {改札|かいさつ} を {出|で}て も いい です か。", zh: "我可以先出站再進來嗎？" },
      ],
    },
    {
      id: "transport-heard-elevator-closed",
      jp: "エレベーター は {今|いま} {使|つか}えません。",
      zh: "電梯現在不能用（維修或施工中）。",
      replies: [
        { jp: "{他|ほか} の エレベーター は あります か。", zh: "有別的電梯嗎？" },
        { jp: "エスカレーター は あります か。", zh: "有手扶梯嗎？" },
      ],
    },
    {
      id: "transport-heard-where-to",
      jp: "どちら まで です か。",
      zh: "要到哪裡？",
      replies: [
        { jp: "この {住所|じゅうしょ} まで お{願|ねが}い します。", zh: "到這個地址（給對方看）" },
        { jp: "この {駅|えき} まで です。", zh: "到這一站（給對方看站名）" },
      ],
    },
    {
      id: "transport-heard-transfer",
      jp: "{次|つぎ} の {駅|えき} で {乗|の}り{換|か}えて ください。",
      zh: "請在下一站換車。",
      replies: [
        { jp: "わかりました。", zh: "知道了" },
        { jp: "{何線|なにせん} に {乗|の}り{換|か}えます か。", zh: "要換哪一條線？" },
      ],
    },
    {
      id: "transport-heard-other-platform",
      jp: "{反対側|はんたいがわ} の ホーム です。",
      zh: "在對面的月台。",
      replies: [
        { jp: "わかりました。", zh: "知道了" },
        { jp: "どう {行|い}けば いい です か。", zh: "要怎麼過去？" },
      ],
    },
    {
      id: "transport-heard-pay-difference",
      jp: "{差額|さがく} を お{支払|しはら}い ください。",
      zh: "請補差額。",
      replies: [
        { jp: "いくら です か。", zh: "多少錢？" },
        { jp: "{現金|げんきん} で {払|はら}います。", zh: "我付現金" },
      ],
    },
    {
      id: "transport-heard-not-stop",
      jp: "この {電車|でんしゃ} は {止|と}まりません。",
      zh: "這班車不停那一站。",
      replies: [
        { jp: "どの {電車|でんしゃ} に {乗|の}れば いい です か。", zh: "那我要搭哪一班？" },
        { jp: "わかりました。", zh: "知道了" },
      ],
    },
    {
      id: "transport-heard-seatbelt",
      jp: "シートベルト を お{願|ねが}い します。",
      zh: "（計程車）請繫安全帶。",
      replies: [
        { jp: "はい。", zh: "好" },
        { jp: "{付|つ}け{方|かた} が わかりません。", zh: "我不會繫" },
      ],
    },
  ],
} satisfies Scene;
